name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  command: npx cypress run
                  browser: chrome
